version: '3'

services:
  bitwarden:
    image: vaultwarden/server:latest #swap tag to raspberry to run on a raspberry pi
    container_name: vaultwarden
    ports:
      - "8080:80"
      - "3012:3012"
    volumes:
      - ./data/bitwarden:/data
    restart: on-failure
    environment:
      WEBSOCKET_ENABLED: 'true'
 
  # proxy:
  #   image: caddy:alpine
  #   restart: always
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile:ro
  #     - caddycerts:/root/.caddy
  #     - ./log:/log
  #   ports:
  #     - 80:80
  #     - 443:443
  #   env_file:
  #     - ./proxy.env

# volumes:
#   caddycerts:

  # bw_backup:
  #   image: bruceforce/vaultwarden-backup:latest #swap tag to rpi3 to run on a raspberry pi
  #   container_name: vaultwarden-backup
  #   restart: on-failure
  #   depends_on:
  #     - bitwarden
  #   volumes:
  #     - ./data/bitwarden:/data
  #     - /opt/Bitwarden-Backup:/backup
  #     - /etc/timezone:/etc/timezone:ro
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - DB_FILE=/data/db.sqlite3
  #     - BACKUP_FILE=/backup/backup.sqlite3
  #     - BACKUP_FILE_PERMISSIONS=700
  #     - CRON_TIME=0 1 * * *
  #     - TIMESTAMP=false
  #     - UID=0
  #     - GID=0

